name: Automated testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      # We need Ghostscript for XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
      - name: Install Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.3"
      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install busted
        run: luarocks install busted
      - name: Test citperoc-lua engine
        run: busted --run=citeproc --output=TAP
      - name: Test BibTeX entries
        run: busted test/bibtex-test.lua --output=TAP
      - name: Test BibTeX parser
        run: busted test/bibtex-parser-test.lua --output=TAP
      - name: Test LaTeX parser
        run: busted test/latex-parser-test.lua --output=TAP
      - name: Test LaTeX package
        run: l3build check -q
      - name: Run examples
        run: |
          l3build install
          cd example
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          "$(kpsewhich -var-value=TEXMFHOME)"/scripts/citation-style-language/citeproc-lua.lua example.aux
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          rm example.aux example.bbl
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
