name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:

  test-lua:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    name: Lua Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.3", "5.4"]
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Lua ${{ matrix.luaVersion }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install package
        run: luarocks build

      - name: Install busted
        run: luarocks install busted

      - name: Test citperoc-lua engine
        run: busted --lua=lua --lpath="" --run=citeproc --output=TAP

      - name: Test other Lua modules
        run: busted --lua=lua --lpath="" --output=TAP


  test-tex:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    name: LaTeX Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          package_file: .github/tl_packages

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install busted
        run: luarocks install busted

      - name: Test citperoc-lua engine
        run: busted --run=citeproc --output=TAP

      - name: Test other Lua modules
        run: busted --output=TAP

      - name: Test LaTeX package
        run: l3build ctan

      - name: Upload CTAN archive
        uses: actions/upload-artifact@v3
        with:
          name: ctan-archive
          path: "*-ctan.zip"
          retention-days: 3

      - name: Archive failed test output
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: testfiles
          path: build/**/*.diff
          retention-days: 3

      - name: Run examples
        run: |
          l3build install
          cd examples
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          "$(kpsewhich -var-value=TEXMFHOME)"/scripts/citation-style-language/citeproc-lua.lua example.aux
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          rm example.aux example.bbl
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
