name: Test and release

on:
  push:
  pull_request:

jobs:

  test-lua:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Test with Lua
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.3", "5.4"]
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install package
        run: luarocks build

      - name: Install busted
        run: luarocks install busted

      - name: Test citperoc-lua engine
        run: busted --lua=lua --lpath="" --run=citeproc --output=TAP

      - name: Test other Lua modules
        run: busted --lua=lua --lpath="" --output=TAP


  test-tex:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Test with TeX Live
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # We need Ghostscript for XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript

      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install busted
        run: luarocks install busted

      - name: Test citperoc-lua engine
        run: busted --run=citeproc --output=TAP

      - name: Test other Lua modules
        run: busted --output=TAP

      - name: Test LaTeX package
        run: l3build check -q

      - name: Archive failed test output
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: testfiles
          path: build/**/*.diff
          retention-days: 3

      - name: Run examples
        run: |
          l3build install
          cd examples
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          "$(kpsewhich -var-value=TEXMFHOME)"/scripts/citation-style-language/citeproc-lua.lua example.aux
          pdflatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          rm example.aux example.bbl
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex
          lualatex -file-line-error -halt-on-error -interaction=nonstopmode example.tex


  release-github:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test-lua, test-tex]
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Extract release notes
        run: awk '/^#+ \[/ { if (p) { exit }; if ($2 != "[Unreleased]") { p = 1 } } p' CHANGELOG.md > release-notes.md

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "release-notes.md"
